# Generated by Django 3.2.25 on 2026-03-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20260302_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='assigned_advisor',
            new_name='advisor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
    ]
