# Generated by Django 3.2.25 on 2026-03-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20260302_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='advisor',
            new_name='career_advisor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
