# Generated by Django 3.2.25 on 2026-03-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20260302_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='career_advisor',
        ),
        migrations.AddField(
            model_name='profile',
            name='stream',
            field=models.CharField(choices=[('cloud', 'Cloud Computing'), ('ai', 'Artificial Intelligence'), ('da', 'Data Analytics')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
