# Generated by Django 3.2.25 on 2026-03-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20260304_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('advisor', 'Advisor')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
